"""add cover_image and skills

Revision ID: ff29367a5bcb
Revises: 1bb18e3d9038
Create Date: 2026-03-18 18:33:25.180405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff29367a5bcb'
down_revision = '1bb18e3d9038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('featured')
        batch_op.drop_column('skills')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
